on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-svelte-kit-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E SvelteKit'
jobs:
  chore:
    name: 'Validating SvelteKit'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        # TODO: Modify if the create-svelte command allows arguments.
        yarn init -p
        yarn add create-svelte

        cat > create-svelte.mjs << EOF
        import('create-svelte').then(module => {
          module.create('.', {
            name: '.',
            template: 'default', // or 'skeleton' or 'skeletonlib'
            types: 'checkjs', // or 'typescript' or null;
            prettier: false,
            eslint: false,
            playwright: false,
            vitest: false
          })
        })
        EOF

        yarn node create-svelte.mjs

        yarn
        yarn build
